kind: "AppStack"
apiVersion: "v1"
runConfig:
  cpu: 1
  memoryMiB: 512
  minInstances: 0
  maxInstances: 2
env:
  - variable: NEXT_PUBLIC_SUPABASE_URL
    secret: NEXT_PUBLIC_SUPABASE_URL
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_SUPABASE_ANON_KEY
    secret: NEXT_PUBLIC_SUPABASE_ANON_KEY
    availability:
      - BUILD
      - RUNTIME
  - variable: GROQ_API_KEY
    secret: GROQ_API_KEY
    availability:
      - BUILD
      - RUNTIME
