kind: "AppStack"
apiVersion: "v1"
runConfig:
  cpu: 1
  memoryMiB: 512
  minInstances: 0
  maxInstances: 2
env:
  - variable: NEXT_PUBLIC_SUPABASE_URL
    secret: supabase_url
  - variable: NEXT_PUBLIC_SUPABASE_ANON_KEY
    secret: supabase_anon_key
  - variable: GROQ_API_KEY
    secret: groq_api_key
